[package]
name = "weather-forecaster"
version = "0.1.0"
authors = ["enelson1001 <ednelson5080@gmail>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "weather-forecaster"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
# Logging
log = { version = "0.4", default-features = false }

# ESP specifics
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync", "alloc"] }

# LVGL
lvgl = { version = "0.6.2", default-features = false, features = [
    "embedded_graphics",
    "unsafe_no_autoinit",
    #"lvgl_alloc",
    #"alloc"
] }

lvgl-sys = { version = "0.6.2" }

# Hardware IO Abstraction Layer
embedded-hal = { version = "1.0.0" }
embedded-svc = "0.28"
embedded-sdmmc = "0.7.0"
embedded-graphics-core = "0.4.0"

# Error
anyhow = "1.0"

# Serde
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0"

# Date and Time
chrono = "0.4.31"
chrono-tz = { version = "0.6.2", features = [ "filter-by-regex" ] }


# C String
cstr_core = "0.2.1"

[build-dependencies]
embuild = "0.33"

[patch.crates-io]
lvgl = { git = "https://github.com/enelson1001/lv_binding_rust" }
lvgl-sys = { git = "https://github.com/enelson1001/lv_binding_rust" }
